### PR TITLE
Support F24, moving our deprecated dependencies for RH systems

### PR DESCRIPTION
**Pull request by Enelar**
I am raising this request to open conversation. Currently only fedora 19/20 is supported, and i am hope that someday not retired fedora systems will be supported too.

I am fixed several flaws, like empty repo file, which caused failing of script and so on. For yet not supported systems script patching repo file, making it point into latest supported repo.

And i am also removed 'mod-python', because it is deprecated.
I hope virtualmin is able to handle wsgi only?

Also i replased raw `rpm` commands with `yum/dnf` whenever i meet them. And also i am installing `dnf` if it missing, because it is stable enough to replace yum.

Also i am found virtualmin being unable to install webmin, because universal repository signed with webmin key, and this is wrongly set in repofile.

### CODE REVIEW

**Comment by virtualmin** [comment]
Most of these are great...but basing them on the old version at software.virtualmin.com, instead of the current git version is a problem. ;-)

Undo the "fast forward to latest script distributed from official site by today" commit and we can begin to merge most of these others.

**Comment by swelljoe** [comment]
Just an update on this...

I'm currently working on virtualmin-install.sh for the Virtualmin 6 release. I'm open to pushing Fedora 25 support into the repos (still hesitant, as if I do that *somebody* is gonna deploy it on a server, and it's going to suck for them in a year when it reaches EOL). But, for development, it wouldn't be terrible to have Fedora support.

I've already added a few of the things you've checked in changes for, but will need quite a bit more time to finish going through the list.

I'm leaving it open until I've gone through all of your commits even though it'll never merge cleanly based on the old version from software.virtualmin.com, but, I'll manually re-implement the ones that work.

**Comment by jcameron** [comment]
FYI, I created a Fedora 25 VM for testing a Virtualmin install on, and it basically worked (I think I had to remove one package from install.sh)

**Comment by brichardson1991** [comment]
Just installed Fedora 25 on a new server and went to run the install.

rh-postgresql
rh-postgresql-server
php-mysql
mod_python 

All these are the only packages not available out of the box.

**Comment by swelljoe** [comment]
All of the deps discussed here have been removed, I think. We now no longer install dependencies in the install script, at all. They come from yum groups defined here: https://github.com/virtualmin/virtualmin-yum-groups

I'll welcome help with adding support for Fedora in a week or two, when I get some time to poke at it.

**Pull request closed without merging**
